name: Limit complexity

on:
  push:
    branches: [ master,harsha ]
  pull_request:
    branches: [ master,harsha ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3